// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zadeqpdfjdpisowwdvbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZGVxcGRmamRwaXNvd3dkdmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzMzMTUsImV4cCI6MjA3MTIwOTMxNX0.pD_pFitFogSWZRwnKIcBrai21KF6nZ7PvacwBc87Fr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});